project:
  type: website
  resources:
    - CNAME

website:
  title: "Yee Seng Chan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: writing.qmd
        text: Writing
      - href: about.qmd
        text: About
  page-footer:
    center: "© 2026 Yee Seng Chan"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
